### ISSUE TITLE
[Bug]:  can't launch the local service.

### ISSUE THREAD

**Issue by ghost** [Kuingsmile/word-GPT-Plus#75]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Self-hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

microsoft 365

### 问题重现 | Bug reproduce

1. After config the key and select mode in the setting of localhost:3000, and then click the [start] button, it reports below errors.

Uncaught runtime errors:
×
ERROR
Word is not defined
ReferenceError: Word is not defined
    at getSeletedText (webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/HomePage.vue?vue&type=script&lang=ts&setup=true:160:9)
    at template (webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/HomePage.vue?vue&type=script&lang=ts&setup=true:167:34)
    at StartChat (webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/HomePage.vue?vue&type=script&lang=ts&setup=true:330:7)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:330:19)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:337:17)
    at emit (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:815:5)
    at eval (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6949:45)
    at handleClick (webpack-internal:///./node_modules/element-plus/es/components/button/src/use-button.mjs:69:5)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:330:19)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:337:17)

I use the latest version of main branch for this git repo. I also revert to v0.4.9. It has same issues.

BTW. It seems that my Word doesn't have the add-in in the [Insert] menu.....
It is office 365 2024 version, where can I find the add-in?

**Comment by closeai1984** [comment]
I start the service with command "yarn run serve" in windows CMD and it doesn't have error message for this command.
 DONE  Compiled successfully in 17760ms                                                                         13:08:11


  App running at:
  - Local:   http://localhost:3000/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

No issues found.

**Comment by Kuingsmile** [comment]
do not open it through http://localhost:3000/

intasll following the instruction in readme

![image](https://github.com/user-attachments/assets/16e03dc5-92a5-4a02-996c-79ec8eddbbf9)

Self-hosted
If you want to host the add-in yourself, you will need to clone this repo and install dependencies, then run the project. Need Node.js 16+.

git clone https://github.com/Kuingsmile/Word-GPT-Plus.git
yarn
yarn run serve
[manifest.xml](https://github.com/Kuingsmile/word-GPT-Plus/blob/master/release/self-hosted/manifest.xml)

Then, follow the [Sideload add-in](https://github.com/Kuingsmile/word-GPT-Plus#sideload-add-in) instructions below to install the add-in.

**Comment by closeai1984** [comment]
Thank you....
In fact, I followed the instruction as Self-hosted installation. 
I installed Node.JS with version 20.17.0
C:\WINDOWS\system32>node --version
v20.17.0

Cloned the repo and follow the same steps ...

**Comment by wangwei15-cd** [comment]
> Thank you.... In fact, I followed the instruction as Self-hosted installation. I installed Node.JS with version 20.17.0 C:\WINDOWS\system32>node --version v20.17.0
> 
> Cloned the repo and follow the same steps ...

The same problem.

**Comment by wangwei15-cd** [comment]
> Thank you.... In fact, I followed the instruction as Self-hosted installation. I installed Node.JS with version 20.17.0 C:\WINDOWS\system32>node --version v20.17.0
> 
> Cloned the repo and follow the same steps ...

Have you solved it?
